### ISSUE TITLE
What's the difference between Spyder-pyls and pyls-spyder?

### ISSUE THREAD

**Issue by Greedquest** [spyder-ide/pyls-spyder#29]
Sorry I'm getting muddled between all the pyls pylsp lsp stuff in Spyder, this one is particularly confusing.

Just looking for a brief high levels overview,I found the respective READMEs a bit too technical. In particular what kind of issues can I ask about in each repo?

**Comment by ccordoba12** [comment]
This project (i.e. `pyls-spyder`) is a plugin for the Python language server:

https://github.com/python-lsp/python-lsp-server

At the moment, it provides support to fold cells in the editor and also show them, along with special comments, in Spyder's Outline pane:

![imagen](https://user-images.githubusercontent.com/365293/148655183-63fedffa-5e3e-4c78-8c57-74a59e2a5875.png)

`Spyder-pyls` is an old clone of the previous version of that server, which still contains some useful pull requests that we plan to integrate in `python-lsp-server` at some point. Please don't report issues there.

**Comment by Greedquest** [comment]
@ccordoba12 Thanks, that clears things up a lot. I was confused when I saw python-lsp-server and Spyder-pyls both seemed to be the same thing and both maintained by the Spyder team, but that makes sense now.
