### ISSUE TITLE
should pyls be compatible with arm64 Apple M1

### ISSUE THREAD

**Issue by jbernalr** [spyder-ide/pyls-spyder#30]
currently im facing issues when I try to install pyls in a arm64 M1 architecture? 

unfortunately the only feedback I get is:

`An unexpected error has occurred. Conda has prepared the above report.`

As I have worked with pyls in other platforms I wonder if this may be a know issue.

**Comment by ccordoba12** [comment]
> currently im facing issues when I try to install pyls in a arm64 M1 architecture?

If you refer to the [Python-language-server](https://github.com/python-lsp/python-lsp-server/), that's a pure Python project, so it can be installed in any architecture.

> unfortunately the only feedback I get is:

This is a problem with Conda and not the package itself. Please report that kind of errors here:

https://github.com/ContinuumIO/anaconda-issues/
