### ISSUE TITLE
Some issues with special comments in the outline explorer

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/pyls-spyder#8]
After PR spyder-ide/spyder#13885, a "special comment" is shown in the outline explorer, regardless of the number of consecutive `-` following the `#`.

Before the outline explorer migration to the pyls, a special comment was registered only when there was exactly 4 consecutive `-` following the `#`. I think this rule should be added back in the current implementation of this feature.

For example, the outline explorer is showing special comments for the horizontal separator that are sometimes present in the header of spyder's file.

![image](https://user-images.githubusercontent.com/10170372/98265118-b3da2a80-1f56-11eb-8828-0361bb1cc8f9.png)

## Versions

* Spyder version: 4.2.0.dev0 b7e9cf9b1
* Python version: 3.7.6 64-bit
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

**Comment by eafpres** [comment]
As I understand it, the pattern #### should also work as a special comment, and does not work in 4.2.0

**Comment by jnsebgosselin** [comment]
@ccordoba12 I'm under the impression that this issue is not fully resolved. There is no "Unnamed comment #" added anymore, but the long `-------------...` are still registered as special comment. Is this working as intended? This is with `pyls-spyder` version 0.2.1.

![image](https://user-images.githubusercontent.com/10170372/101216102-f160cf00-364c-11eb-9f76-62964fc57925.png)

**Comment by ccordoba12** [comment]
Please open a new issue about it.
